// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create.sql

package orm

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  auth_id,
  avatar_url,
  bio,
  theme,
  language,
  email_notifications,
  last_login_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, auth_id, avatar_url, bio, theme, language, email_notifications, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	AuthID             pgtype.UUID
	AvatarUrl          pgtype.Text
	Bio                pgtype.Text
	Theme              pgtype.Text
	Language           pgtype.Text
	EmailNotifications pgtype.Bool
	LastLoginAt        pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.AuthID,
		arg.AvatarUrl,
		arg.Bio,
		arg.Theme,
		arg.Language,
		arg.EmailNotifications,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthID,
		&i.AvatarUrl,
		&i.Bio,
		&i.Theme,
		&i.Language,
		&i.EmailNotifications,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
