// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orm

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                 pgtype.UUID
	AuthID             pgtype.UUID
	AvatarUrl          pgtype.Text
	Bio                pgtype.Text
	Theme              pgtype.Text
	Language           pgtype.Text
	EmailNotifications pgtype.Bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastLoginAt        pgtype.Timestamptz
}
