// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orm

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       pgtype.UUID
	Username string
	Email    string
	Password string
	Role     string
}
