FROM golang:1.26-alpine

RUN apk add --no-cache git && \
    go install github.com/air-verse/air@latest && \
    go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.18.1

WORKDIR /workspace

COPY go.mod go.sum ./
COPY pkg/ ./pkg/
COPY services/people/ ./services/people/

RUN printf 'go 1.26.1\n\nuse (\n\t.\n\t./services/people\n)\n' > go.work
RUN go work sync && cd services/people && go mod download

WORKDIR /workspace/services/people

ENTRYPOINT ["sh", "scripts/entrypoint.dev.sh"]
